name: Docker workflow for project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/project .

    - name: DockerHub credentials
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/project