name: Generate and preprocess the data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs after every hour
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Setup DVC
        run: |
          pip install dvc
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local \
            gdrive_service_account_json_file_path GD_credentials.json

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull data from DVC remote
        run: |
          dvc pull data/dummy_sensor_data.csv.dvc

      - name: Run DVC repro
        run: |
          dvc repro
    
      - name: DVC Add
        run: |
          dvc add data/dummy_sensor_data.csv model.pkl
        
      - name: Push data to DVC remote
        run: |
          dvc push -r myremote

      - name: Git credentials
        run: |
          git config --global user.email "tradersbismillah282@gmail.com"
          git config --global user.name "BismillahTraders-BT"
  
      - name: Make changes to Git
        run: |
          git pull origin main
          git add .
          git commit -m "Update data"
          git push origin main