name: Generate and preprocess the data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Setup DVC
        run: |
          pip install dvc
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local gdrive_service_account_json_file_path GD_Credentials.json

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull data from DVC remote
        run: |
          dvc pull -r myremote --force

      - name: Run DVC repro
        run: |
          dvc repro
      
      - name: Git credentials
        run: |
          git config --global user.email "tradersbismillah282@gmail.com"
          git config --global user.name "BismillahTraders-BT"

      - name: Add changes to Git
        run: |
          git add .

      - name: Remove model.pkl from Git tracking
        run: |
          git rm -r --cached model.pkl
          git commit -m "Stop tracking model.pkl"

      - name: DVC Add
        run: |
          dvc add data/dummy_sensor_data.csv model.pkl

      - name: Push data to DVC remote
        run: |
          dvc push -r myremote
          
      - name: Commit changes to Git
        run: |
          git commit -m "Update data"
          git push origin main
